apiVersion: v1
kind: ReplicationController
metadata:
  name: juliatan-master
  labels:
    app: juliatan
    role: master
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: juliatan
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: codeneomatrix/julia-tan  # or just image: juliatan
        #build: .
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: DISCORD_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-token
              key: DISCORD_BOT_TOKEN            