apiVersion: v1
kind: ReplicationController
metadata:
  name: juliatan-master
  labels:
    app: juliatan
    role: master
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: juliatan
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        #image: juliatan  # or just image: juliatan
        build: .
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: DISCORD_BOT_TOKEN
            key: token            