apiVersion: v1
kind: Service
metadata:
  name: juliatan-master
  labels:
    app: juliatan
    role: master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379  
  selector:
    app: juliatan
    role: master
    tier: backend